# Generated by Django 4.1 on 2022-09-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oder", "0002_rename_quantity_cartdeitl_quantiity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartdeitl",
            name="total",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
