# Generated by Django 4.1 on 2022-11-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oder", "0003_cartdeitl_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdeitl",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
