# Generated by Django 4.1 on 2022-11-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oder", "0004_alter_cartdeitl_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdeitl",
            name="total",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
