# Generated by Django 4.1 on 2022-11-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oder", "0005_alter_cartdeitl_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartdeitl",
            name="quantiity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
