# Generated by Django 4.1 on 2022-11-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oder", "0006_alter_cartdeitl_quantiity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oders",
            name="deilevry_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
