# Generated by Django 4.1 on 2022-11-12 15:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("oder", "0007_alter_oders_deilevry_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("quantiity", models.IntegerField()),
                ("value", models.FloatField()),
                ("form_date", models.DateField(default=django.utils.timezone.now)),
                ("to_date", models.DateField(default=django.utils.timezone.now)),
                ("is_valid", models.BooleanField(default=True)),
            ],
        ),
    ]
