# Generated by Django 4.1 on 2022-09-19 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proflie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='users')),
                ('code', models.BooleanField(default=False)),
                ('code_used', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_Proflie', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'home'), ('office', 'office'), ('acdemy', 'acdemy'), ('bussins', 'businss')], max_length=10)),
                ('phone_num', models.IntegerField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_number', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('home', 'home'), ('office', 'office'), ('acdemy', 'acdemy'), ('bussins', 'businss')], max_length=10)),
                ('countery', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=25)),
                ('street', models.CharField(max_length=25)),
                ('reogin', models.CharField(max_length=25)),
                ('notes', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_Adderrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
