# Generated by Django 4.1 on 2022-09-19 23:41

from django.db import migrations, models
import utils.code_grente


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proflie',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proflie',
            name='code',
            field=models.CharField(default=utils.code_grente.grente_code, max_length=10),
        ),
    ]
