# Generated by Django 4.1 on 2022-08-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo')),
                ('call_us', models.TextField(max_length=25)),
                ('email_us', models.TextField(max_length=25)),
                ('fb_link', models.URLField(blank=True, null=True)),
                ('tw_link', models.URLField(blank=True, null=True)),
                ('li_link', models.URLField(blank=True, null=True)),
                ('in_link', models.URLField(blank=True, null=True)),
                ('pen_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
