# Generated by Django 4.1 on 2022-08-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='adderrs',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='app_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
