# Generated by Django 4.1 on 2022-08-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_company_adderrs_company_app_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
