# Generated by Django 4.1 on 2022-08-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='dec',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='subtitle',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
