# Generated by Django 4.1 on 2022-08-28 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Brand_name')),
                ('image', models.ImageField(upload_to='Brand', verbose_name='Brand_images')),
            ],
        ),
        migrations.CreateModel(
            name='Catgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Catgory_name')),
                ('image', models.ImageField(upload_to='Cagtory', verbose_name='Catgory_images')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('sku', models.IntegerField(verbose_name='SKU')),
                ('price', models.FloatField(verbose_name='Price')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('dec', models.CharField(max_length=300, verbose_name='dec')),
                ('subtitle', models.CharField(max_length=150, verbose_name='subtitle')),
                ('flags', models.CharField(choices=[('New', 'New'), ('Sale', 'Slae'), ('Fature', 'Fature')], max_length=10, verbose_name='Flags')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video_url')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_product', to='products.brand', verbose_name='Brand')),
                ('catgory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Catgory_prodcut', to='products.catgory', verbose_name='Catgory')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Reviw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commnt', models.CharField(max_length=300, verbose_name='commnet')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('create_at', models.DateField(default=django.utils.timezone.now, verbose_name='create_at')),
                ('products', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.products', verbose_name='product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='ProductsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='productimages', verbose_name='image')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Product_image')),
            ],
        ),
    ]
