# Generated by Django 4.1 on 2022-08-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='dec',
            field=models.TextField(max_length=300, verbose_name='dec'),
        ),
    ]
