# Generated by Django 4.1 on 2022-09-16 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_products_qounitiy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviw',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proudct_review', to='products.products', verbose_name='product_review'),
        ),
    ]
